spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/onboarding
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  thread-executor: virtual
